# quizzes = [
#   { title: 'The Avengers', image_path: 'assets/avengers' },
#   { title: 'Avengers:Age of Ultron', image_path: 'assets/avengers2' },
#   { title: 'Iron Man', image_path: 'assets/ironman' },
#   { title: 'Iron Man 2', image_path: 'assets/ironman2' },
#   { title: 'Thor', image_path: 'assets/thor' },
#   { title: 'Thor: The Dark World', image_path: 'assets/thor2' },
#   { title: 'Captain America: The First Avenger', image_path: 'assets/captainamerica' },
#   { title: 'Captain America: The Winter Soldier', image_path: 'assets/captainamerica2' }
# ]

# questions = [
#   { text: ['In the movie Avengers, what does Steve Rogers discovers in the reserves of the S.H.I.E.L.D.?',
#            'Which character catches Iron man when he falls at the end of the Avengers movie?',
#            'What is the name of the alien race that attacks New York as soon as the portal is opened?',
#            'In which city does the first confrontation between certain Avengers and Loki take place?',
#            'Where Natasha Romanoff and Bruce Banner First Met?'],
#     category: ['ca', "im", null, null, null],
#     correct_answer: ['HYDRA Weapons', 'Hulk', 'The Chitauri', 'Stuttgart', 'Calcutta'] },
#   { text: ['In the movie Avengers: Age of Ultron, what Tony sees in his vision?',
#            'Who eliminates the last robot Ultron?',
#            'According to Thor, in Avengers: Age of Ultron what Jane Foster got?',
#            'Which infinity stone does Vision wear on his forehead?',
#            'Which city does Tony Stark travel to in Avengers: Age of Ultron to find traces of Ultron on the internet?'],
#     category: ['im', null, 'th', null, 'im'],
#     correct_answer: ['The Avengers dead and the Chitauri invading Earth', 'Vision', 'A Nobel Prize', 'Mind', 'Oslo'] },
#   { text: ["What is the name of Tony Stark's best friend?",
#            'What rock band is some of the music in the film from?',
#            'In Iron Man, Tony Stark is suspicious of Stane and asks someone to spy on him. Who does he ask?',
#            'In total, how many armors are created by Tony Stark in Iron Man?',
#            "What is the core of Tony Stark's ARC Reactor?"],
#     category: ['im', null, 'im', 'im', 'im'],
#     correct_answer: ['James Rhodes', 'ACDC', 'Pepper Potts', '3', 'Palladium'] },
#   { text: ["What is the name of Tony Stark's father?",
#            'Where does the Formula 1 race take place in Iron Man 2?',
#            'What does Pepper Potts do when Tony Stark manages to save her at the end of the film?',
#            'With what armor does Tony manage to defeat Ivan Vanko in Iron Man 2?',
#            'What event takes place at the beginning of the film?'],
#     category: ['im', 'im', null, 'im', null],
#     correct_answer: ['Howard', 'Monaco', 'She resigns', 'Mark 6', 'Stark Expo'] },
#   { text: ['How Thor explains to Jane how the Nine Realms work?',
#            'Where is Loki from?',
#            'Why does Thor end up on Earth in the first Thor movie?',
#            'What is the name of the scientist who helps Jane Foster?',
#            "In the first Thor movie, Jötunheims interrupt Thor's coronation. How many are they?"],
#     category: ['th', null, 'th', null, 'th'],
#     correct_answer: ['By drawing', 'Jotun', 'Because he was exiled by Odin', 'Erik Selvig', '3'] },
#   { text: ["Who is Odin's father?",
#            'What is the name of the Dark Elf world?',
#            'In Thor: The Dark World, Loki asks Thor to have faith in...?',
#            'In Thor: The Dark World, how do Thor, Loki and Jane leave Asgard?',
#            'Which other Avenger makes a short appearance in In Thor: The Dark World?'],
#     category: [null, null, 'th', 'th', null],
#     correct_answer: ['Bor', 'Svartalfheim', 'His anger', 'Through a secret passage only known to Loki', 'Captain America'] },
#   { text: ['Who is behind the creation of the new Captain America costume?',
#            'In Captain America: The First Avenger, what war did Steve Rogers fight in?',
#            'What neighborhood is Steve Rogers from?',
#            "What is Agent Carter's first name?",
#            "What material was Captain America's shield made from?"],
#     category: ['ca', 'ca', 'ca', null, 'ca'],
#     correct_answer: ['Phil Coulson', 'Second World War', 'Brooklyn', 'Peggy', 'Vibranium'] },
#   { text: ['Who motivates Steve Rogers to join S.H.I.E.L.D.?',
#            'What is the first line of dialogue in the film?',
#            'What is the name of the companion of Sam Wilson who tragically lost his life during a mission?',
#            'When Steve and Natasha discover an elevator at Camp Lehigh in Captain America: The Winter Soldier, what code is displayed to access it?',
#            "Who comes to the aid of Steve, Sam and Natasha in Hydra's van in Captain America: The Winter Soldier?"],
#     category: ['ca', null, null, 'ca', 'ca'],
#     correct_answer: ['Peggy Carter', 'On your left', 'Riley', '8542', 'Maria Hill'] }
# ]

# options = [
#   { content: [['HYDRA Weapons', 'Bombs', 'Super soldier serum', 'An Infinity Stone'],
#               ['Thor', 'Hulk', 'Fury', 'Hawkeye'],
#               ['The Outriders', 'The Chitauri', 'The Skrulls', 'The Sakaarans'],
#               ['Berlin', 'Paris', 'Prague', 'Stuttgart'],
#               ['Calcutta', 'Bombay', 'New Dehli', 'Jaipur']] },
#   { content: [['The future', 'Ultron', 'The Avengers dead and the Chitauri invading Earth', "Thanos' arrival"],
#               ['Iron Man', 'Thor', 'Hulk', 'Vision'],
#               ['An Albert Einstein Prize', 'A Nobel Prize', 'A scientist position at Stark Industries', 'A Copley medal (= a scientific prize)'],
#               ['Soul', 'Power', 'Reality', 'Mind'],
#               ['Copenhagen', 'Oslo', 'London', 'Berlin']] },
#   { content: [['James Rhodes', 'Happy Hogan', 'Obadiah Stane', 'Bruce Banner'],
#               ['Queen', 'ACDC', 'Nirvana', 'Led Zeppelin'],
#               ['Colonel James Rhodes', 'Happy Hogan', 'Pepper Potts', 'Phil Coulson'],
#               ['3', '1', '4', '2'],
#               ['Titanium', 'Palladium', 'Terranium', 'Uranium']] },
#   { content: [['Howard', 'James', 'Anthony', 'Ward'],
#               ['Miami', 'Monaco', 'Dubai', 'Silverstone'],
#               ['She kisses him', 'She resigns', 'She insults him', 'She hits him'],
#               ['Mark 3', 'Mark 5', 'Mark 6', 'Mark 7'],
#               ['Arrival of SHIELD', 'Stark Expo', 'The Mandarin Attack', "Tony Stark's birthday"]] },
#   { content: [['Writing in the ground', 'Showing the stars', 'By drawing', 'By miming'],
#               ['Asgardian', 'Dokkalfars', 'Vanes', 'Jotun'],
#               ['For an initiatory journey', 'Because he was exiled by Odin', 'To fetch lost Mjolnir there', 'To fetch Loki'],
#               ['Abraham Erskine', 'Erik Selvig', 'Roger Dooley', 'John Flynn'],
#               ['2', '3', '4', '5']] },
#   { content: [['Hor', 'Gor', 'Bor', "He doesn't have one"],
#              ['Svartalfheim', 'Jotunheim', 'Alfheim', 'Vanaheim'],
#              ['His strength', 'His courage', 'His anger', 'His vision'],
#              ['They manage to pass through the Bifrost', 'Using Mjolnir', 'Through a secret passage only known to Loki', 'Through black magic'],
#              ['Hulk', 'Black Widow', 'Captain America', 'Hawkeye']] },
#   { content: [['Nick Fury', 'Maria Hill', 'Phil Coulson', 'Tony Stark'],
#               ['First World War', 'Second World War', 'Battle of Tonsberg', 'Cold War'],
#               ['Brooklyn', 'Manhattan', 'New Jersey', 'Queens'],
#               ['Sharon', 'Sarah', 'Peggy', 'Penny'],
#               ['Vibranium', 'Metal', 'Uru', 'Adamantium']] },
#   { content: [['Nick Fury', 'Tony Stark', 'Peggy Carter', 'Howard Stark'],
#               ['On your left', "I'm calling an ambulance", 'I had to drag at the start', 'My name is Sam Wilson'],
#               ['Ben', 'Roster', 'Riley', 'Billy'],
#               ['5323', '6698', '8542', '2014'],
#               ['Nick Fury', 'Brock Rumlow', 'Maria Hill', 'Georges Batroc']] }
# ]

quizzes = [
  { title: "The Avengers", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897823/avengers_xm6m4o.jpg",
    questions: [ { text: "In the movie Avengers, what does Steve Rogers discovers in the reserves of the S.H.I.E.L.D.?",
                   category: "ca", correct_answer: "HYDRA Weapons",
                   options: ['HYDRA Weapons', 'Bombs', 'Super soldier serum', 'An Infinity Stone']},
                 { text: "Which character catches Iron man when he falls at the end of the Avengers movie?",
                   category: "im", correct_answer: "Hulk",
                   options: ['Thor', 'Hulk', 'Fury', 'Hawkeye']},
                 { text: "What is the name of the alien race that attacks New York as soon as the portal is opened?",
                   category: "", correct_answer: "The Chitauri",
                   options: ['The Outriders', 'The Chitauri', 'The Skrulls', 'The Sakaarans']},
                 { text: "In which city does the first confrontation between certain Avengers and Loki take place?",
                   category: "", correct_answer: "Stuttgart",
                   options: ['Berlin', 'Paris', 'Prague', 'Stuttgart']},
                 { text: "Where Natasha Romanoff and Bruce Banner First Met?",
                   category: "", correct_answer: "Calcutta",
                   options: ['Calcutta', 'Bombay', 'New Dehli', 'Jaipur']}]},
  { title: "Avengers:Age of Ultron", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897337/avengers2_buf2qb.jpg",
    questions: [ { text: "In the movie Avengers: Age of Ultron, what Tony sees in his vision?",
                   category: "im", correct_answer: "The Avengers dead and the Chitauri invading Earth",
                   options: ['The future', 'Ultron', 'The Avengers dead and the Chitauri invading Earth', "Thanos' arrival"]},
                 { text: "Who eliminates the last robot Ultron?",
                   category: "", correct_answer: "Vision",
                   options: ['Iron Man', 'Thor', 'Hulk', 'Vision']},
                 { text: "According to Thor, in Avengers: Age of Ultron what Jane Foster got?",
                   category: "th", correct_answer: "A Nobel Prize",
                   options: ['An Albert Einstein Prize', 'A Nobel Prize', 'A scientist position at Stark Industries', 'A Copley medal (= a scientific prize)']},
                 { text: "Which infinity stone does Vision wear on his forehead?",
                   category: "", correct_answer: "Mind",
                   options: ['Soul', 'Power', 'Reality', 'Mind']},
                 { text: "Which city does Tony Stark travel to in Avengers: Age of Ultron to find traces of Ultron on the internet?",
                   category: "im", correct_answer: "Oslo",
                   options: ['Copenhagen', 'Oslo', 'London', 'Berlin']}]},
  { title: "Iron Man", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897338/ironman_tek4ks.jpg",
    questions: [ { text: "What is the name of Tony Stark's best friend?",
                   category: "im", correct_answer: "James Rhodes",
                   options: ['James Rhodes', 'Happy Hogan', 'Obadiah Stane', 'Bruce Banner']},
                 { text: "What rock band is some of the music in the film from?",
                   category: "", correct_answer: "ACDC",
                   options: ['Queen', 'ACDC', 'Nirvana', 'Led Zeppelin']},
                 { text: "In Iron Man, Tony Stark is suspicious of Stane and asks someone to spy on him. Who does he ask?",
                   category: "im", correct_answer: "Pepper Potts",
                   options: ['Colonel James Rhodes', 'Happy Hogan', 'Pepper Potts', 'Phil Coulson']},
                 { text: "In total, how many armors are created by Tony Stark in Iron Man?",
                   category: "im", correct_answer: "3",
                   options: ['3', '1', '4', '2']},
                 { text: "What is the core of Tony Stark's ARC Reactor?",
                   category: "im", correct_answer: "Palladium",
                   options: ['Titanium', 'Palladium', 'Terranium', 'Uranium']}]},
  { title: "Iron Man 2", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648898633/ironman2_liz2uh.jpg",
    questions: [ { text: "What is the name of Tony Stark's father?",
                   category: "im", correct_answer: "Howard",
                   options: ['Howard', 'James', 'Anthony', 'Ward']},
                 { text: "Where does the Formula 1 race take place in Iron Man 2?",
                   category: "im", correct_answer: "Monaco",
                   options: ['Miami', 'Monaco', 'Dubai', 'Silverstone']},
                 { text: "What does Pepper Potts do when Tony Stark manages to save her at the end of the film?",
                   category: "", correct_answer: "She resigns",
                   options: ['She kisses him', 'She resigns', 'She insults him', 'She hits him']},
                 { text: "With what armor does Tony manage to defeat Ivan Vanko in Iron Man 2?",
                   category: "im", correct_answer: "Mark 6",
                   options: ['Mark 3', 'Mark 5', 'Mark 6', 'Mark 7']},
                 { text: "What event takes place at the beginning of the film?",
                   category: "", correct_answer: "Stark Expo",
                   options: ['Arrival of SHIELD', 'Stark Expo', 'The Mandarin Attack', "Tony Stark's birthday"]}]},
  { title: "Thor", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897337/thor_fpmpa9.jpg",
    questions: [ { text: "How Thor explains to Jane how the Nine Realms work?",
                   category: "th", correct_answer: "By drawing",
                   options: ['Writing in the ground', 'Showing the stars', 'By drawing', 'By miming']},
                 { text: "Where is Loki from?",
                   category: "", correct_answer: "Jotun",
                   options: ['Asgardian', 'Dokkalfars', 'Vanes', 'Jotun']},
                 { text: "Why does Thor end up on Earth in the first Thor movie?",
                   category: "th", correct_answer: "Because he was exiled by Odin",
                   options: ['For an initiatory journey', 'Because he was exiled by Odin', 'To fetch lost Mjolnir there', 'To fetch Loki']},
                 { text: "What is the name of the scientist who helps Jane Foster?",
                   category: "", correct_answer: "Erik Selvig",
                   options: ['Abraham Erskine', 'Erik Selvig', 'Roger Dooley', 'John Flynn']},
                 { text: "In the first Thor movie, Jötunheims interrupt Thor's coronation. How many are they?",
                   category: "th", correct_answer: "3",
                   options: ['2', '3', '4', '5']}]},
  { title: "Thor: The Dark World", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897338/thor2_bhhkpx.jpg",
    questions: [ { text: "Who is Odin's father?",
                   category: "", correct_answer: "Bor",
                   options: ['Hor', 'Gor', 'Bor', "He doesn't have one"]},
                 { text: "What is the name of the Dark Elf world?",
                   category: "", correct_answer: "Svartalfheim",
                   options: ['Svartalfheim', 'Jotunheim', 'Alfheim', 'Vanaheim']},
                 { text: "In Thor: The Dark World, Loki asks Thor to have faith insrc.?",
                   category: "th", correct_answer: "His anger",
                   options: ['His strength', 'His courage', 'His anger', 'His vision']},
                 { text: "In Thor: The Dark World, how do Thor, Loki and Jane leave Asgard?",
                   category: "th", correct_answer: "Through a secret passage only known to Loki",
                   options: ['They manage to pass through the Bifrost', 'Using Mjolnir', 'Through a secret passage only known to Loki', 'Through black magic']},
                 { text: "Which other Avenger makes a short appearance in In Thor: The Dark World?",
                   category: "", correct_answer: "Captain America",
                   options: ['Hulk', 'Black Widow', 'Captain America', 'Hawkeye']}]},
  { title: "Captain America: The First Avenger", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897337/captainamerica_cxyefh.jpg",
    questions: [ { text: "Who is behind the creation of the new Captain America costume?",
                   category: "ca", correct_answer: "Phil Coulson",
                   options: ['Nick Fury', 'Maria Hill', 'Phil Coulson', 'Tony Stark']},
                 { text: "In Captain America: The First Avenger, what war did Steve Rogers fight in?",
                   category: "ca", correct_answer: "Second World War",
                   options: ['First World War', 'Second World War', 'Battle of Tonsberg', 'Cold War']},
                 { text: "What neighborhood is Steve Rogers from?",
                   category: "ca", correct_answer: "Brooklyn",
                   options: ['Brooklyn', 'Manhattan', 'New Jersey', 'Queens']},
                 { text: "What is Agent Carter's first name?",
                   category: "", correct_answer: "Peggy",
                   options: ['Sharon', 'Sarah', 'Peggy', 'Penny']},
                 { text: "What material was Captain America's shield made from?",
                   category: "ca", correct_answer: "Vibranium",
                   options: ['Vibranium', 'Metal', 'Uru', 'Adamantium']}]},
  { title: "Captain America: The Winter Soldier", image_path: "https://res.cloudinary.com/dyanmaz/image/upload/c_scale,h_320,w_480/v1648897337/captainamerica2_yacszd.jpg",
    questions: [ { text: "Who motivates Steve Rogers to join S.H.I.E.L.D.?",
                   category: "ca", correct_answer: "Peggy Carter",
                   options: ['Nick Fury', 'Tony Stark', 'Peggy Carter', 'Howard Stark']},
                 { text: "What is the first line of dialogue in the film?",
                   category: "", correct_answer: "On your left",
                   options: ['On your left', "I'm calling an ambulance", 'I had to drag at the start', 'My name is Sam Wilson']},
                 { text: "What is the name of the companion of Sam Wilson who tragically lost his life during a mission?",
                   category: "", correct_answer: "Riley",
                   options: ['Ben', 'Roster', 'Riley', 'Billy']},
                 { text: "When Steve and Natasha discover an elevator at Camp Lehigh in Captain America: The Winter Soldier, what code is displayed to access it?",
                   category: "ca", correct_answer: "8542",
                   options: ['5323', '6698', '8542', '2014']},
                 { text: "Who comes to the aid of Steve, Sam and Natasha in Hydra's van in Captain America: The Winter Soldier?",
                   category: "ca", correct_answer: "Maria Hill",
                   options: ['Nick Fury', 'Brock Rumlow', 'Maria Hill', 'Georges Batroc']}]}
]

quizzes.each do |quiz|
  quiz_new = Quiz.create(
    title: quiz[:title],
    image_path: quiz[:image_path]
  )
  quiz[:questions].each do |question|
    question_new = Question.create(
        text: question[:text],
        category: question[:category],
        correct_answer: question[:correct_answer],
        quiz: quiz_new
    )
    question[:options].each do |option|
      Option.create(
        content: option,
        question: question_new
      )
    end
  end
end
